#######################################################
# Check dockerhub for updates to the tomcat container #
#######################################################

name: Check For Upstream Updates

on:
  schedule:
    # Once a day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  checkUpstream:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables
      run: |
        echo "scriptsdir=.github/helperScripts" >> $GITHUB_ENV

    - name: Checkout default branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify repo has been cloned
      run: |
        git status
        git branch -a
        git remote -v

    - name: Grab the most recent upstream version:
      run: |
        echo $( ${{ env.scriptsdir }}/dockertags.sh rockylinux | grep -v "latest" | sort -Vr)
        upstream=$( ${{ env.scriptsdir }}/dockertags.sh rockylinux | grep -v "latest" | sort -Vr | head -n1)
        echo $upstream
        echo "upstream=$upstream" >> $GITHUB_ENV

    - name: Update to most recent version, if necessary
      run: |
        echo ${{ env.upstream }}
        git branch -a
        git branch -a | grep "${{ env.upstream }}" &&
        echo "Already up to date with upstream: ${{ env.upstream }}" ||
        {
        echo "New upstream version ${{ env.upstream }}"
        current=$(git branch -r | grep -v "latest" | sort -Vr | head -n1)
        echo "Most recent unidata/rockylinux version: $current"
        git checkout -b ${{ env.upstream }} $current
        git status
        sed -e "s/from rockylinux:.*/from rockylinux:$upstream/g" Dockerfile -i
        cat Dockerfile
        echo "Now to figure out how to commit and push changes..."
        }
